openapi: 3.0.3
info:
  title: Matching Service
  version: 0.1.0
servers:
  - url: http://localhost:8084/api
paths:
  /matches:
    get:
      summary: Get trip matches for the current user (basic score)
      security:
        - bearerAuth: []
      description: Requires Authorization header. Example: `Authorization: Bearer eyJ...`
      parameters:
        - in: query
          name: destinationSedeId
          schema:
            type: string
        - in: query
          name: time
          schema:
            type: string
            format: time
      responses:
        '200':
          description: List of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '401':
          description: Unauthorized (missing or invalid JWT)
        '403':
          description: Forbidden (insufficient permissions)
  /matches/{id}/accept:
    put:
      summary: Accept a match
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Match accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
  /matches/{id}/reject:
    put:
      summary: Reject a match
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Match rejected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Match:
      type: object
      properties:
        tripId:
          type: string
          format: uuid
        driverId:
          type: string
        score:
          type: number
        status:
          type: string
