openapi: 3.0.3
info:
  title: Matching Service
  version: 0.1.0
servers:
  - url: http://localhost:8084/api
paths:
  /matches:
    get:
      summary: Get trip matches for the current user (directional)
      security:
        - bearerAuth: []
      description: Requires Authorization header. Example: `Authorization: Bearer eyJ...`
      parameters:
        - in: query
          name: destinationSedeId
          schema:
            type: string
          description: Required when direction is TO_SEDE
        - in: query
          name: originSedeId
          schema:
            type: string
          description: Required when direction is FROM_SEDE
        - in: query
          name: time
          schema:
            type: string
            format: time
          description: Preferred time in HH:mm (local user timezone)
        - in: query
          name: origin
          schema:
            type: string
          description: Optional origin description (proximity scoring)
        - in: query
          name: direction
          required: true
          schema:
            type: string
            enum: [TO_SEDE, FROM_SEDE]
          description: >-
            Direction of travel. When TO_SEDE, destinationSedeId is required.
            When FROM_SEDE, originSedeId is required.
        - in: header
          name: Accept-Language
          required: false
          schema:
            type: string
          description: Language for localized error messages
      responses:
        '200':
          description: List of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '400':
          description: Bad request (e.g., missing required parameters based on direction)
        '401':
          description: Unauthorized (missing or invalid JWT)
        '403':
          description: Forbidden (insufficient permissions)
  /matches/{id}/accept:
    put:
      summary: Accept a match
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Match accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
  /matches/{id}/reject:
    put:
      summary: Reject a match
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Match rejected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Match:
      type: object
      properties:
        tripId:
          type: string
          format: uuid
        driverId:
          type: string
        score:
          type: number
        status:
          type: string
